---
title: "Qualifying Exam 2017"
subtitle: "Take Home Question 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



This part of the exam requires you to describe, execute, and interpret a data analysis.  The data were obtained in a survey of students math and portuguese language courses in secondary school. It contains a lot of interesting social, gender and study information about students.  Develop a model that can predict the score of students in mathematics and portuguese language courses based on predictors that you identify as having a significant impact on the outcome.

Because the model is intended for use in a teaching setting, you will want to make sure that it generalizes beyond this data set. In other words, the measures of predictive performance that you report need to account for potential overfitting from not having a validation dataset. Your report should include a discussion of the
important factors and their impact on predictions as well as a description of model performance. Both tables
and graphs may be helpful.

While there are many different ways you can model the data, you will not have time to try everything.
Develop a reasonable model and if there are additional forms you do not have time to try but believe would
be important to investigate, describe them in your report as future work that could be done.

Your responses should be self contained so that readers do not have to search through the exam to find
relevant output. Feel free to cut and paste from computer output, but please make sure tables and/or graphs
are properly formatted and easy to read. Be succinct. Your report probably does not need to exceed 5 pages.
You do not need to summarize every step you took, but should describe clearly your final results including:

- Description and justification of analytic method
- Summary of key findings with a plain language summary abstract that explains major results to a non-
technical reader.
- Tables and/or figures as needed
- An appendix that includes the computer programs used to carry out the analyses. Please annotate the program to indicate which parts were used to answer specific items. This will help the grader when an answer differs from what is expected.


## Codebook

Attributes for both student-mat.csv (Math course) and student-por.csv (Portuguese language course) datasets:




| Variable Name | Description  |
| ------------- | ------------------------------------------------------------------------------  |
| school | student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira) | 
| sex | student's sex (binary: 'F' - female or 'M' - male) | 
| age | student's age (numeric: from 15 to 22) | 
| address | student's home address type (binary: 'U' - urban or 'R' - rural) | 
| famsize | family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3) | 
| Pstatus | parent's cohabitation status (binary: 'T' - living together or 'A' - apart) | 
| Medu |  mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education) | 
| Fedu | father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education) | 
| Mjob | mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other') | 
| Fjob | father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other') | 
| reason | reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other') | 
| guardian | student's guardian (nominal: 'mother', 'father' or 'other') | 
| traveltime | home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour) | 
| studytime | weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours) | | failures | number of past class failures (numeric: n if 1<=n<3, else 4) | 
| schoolsup | extra educational support (binary: yes or no) | 
| famsup | family educational support (binary: yes or no) | 
| paid | extra paid classes within the course subject (Math or Portuguese) (binary: yes or no) | 
| activities | extra-curricular activities (binary: yes or no) | 
| nursery | attended nursery school (binary: yes or no) | 
| higher | wants to take higher education (binary: yes or no) | 
| internet | Internet access at home (binary: yes or no) | 
| romantic | with a romantic relationship (binary: yes or no) | 
| famrel | quality of family relationships (numeric: from 1 - very bad to 5 - excellent) | 
| freetime | free time after school (numeric: from 1 - very low to 5 - very high) | 
| goout | going out with friends (numeric: from 1 - very low to 5 - very high) | 
| Dalc | workday alcohol consumption (numeric: from 1 - very low to 5 - very high) | 
| Walc | weekend alcohol consumption (numeric: from 1 - very low to 5 - very high) | 
| health | current health status (numeric: from 1 - very bad to 5 - very good) | 
| absences | number of school absences (numeric: from 0 to 93) | 

These grades are related with the course subject, Math or Portuguese:

| Grade | Description |
| ----- | -------------------------------------------|
| G1 | first period grade (numeric: from 0 to 20) |
| G2 | second period grade (numeric: from 0 to 20) | 
| G3 | final grade (numeric: from 0 to 20, output target) | 


**Additional note**: there are several (382) students that belong to both datasets . These students can be identified by searching for identical attributes that characterize each student, as shown in the annexed R file.

Source Information

P. Cortez and A. Silva. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp. 5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7.

Fabio Pagnotta, Hossain Mohammad Amran. Email:fabio.pagnotta@studenti.unicam.it, mohammadamra.hossain '@' studenti.unicam.it University Of Camerino

[Student Performance Data](https://archive.ics.uci.edu/ml/datasets/Student+Performance)