# Load Data for 2002
hhold <- read.delim("2002/hhold.tab", sep = "\t") 
morbidty <- read.delim("2002/morbidty.tab", sep = "\t") 
mother <- read.delim("2002/mother.tab", sep = "\t") 
person <- read.delim("2002/person.tab", sep = "\t") 
secreen <- read.delim("2002/secreen.tab", sep = "\t") 

#Select only moms from 2002 data
person <- person[person$relmom==32, ]

# Remove duplicate rows from "mothers" (same mother has 2 rows, one for each child)
## select columns that are not about children (and thus, will be the identical for a mother)
## 2113 rows initially - 11 duplicates = 2102 rows
mother <- mother[ , c(1:8, 14, 32, 33, 203, 204)]
sum(duplicated(mother))
mother <- mother[!duplicated(mother), ]

# Fix data entry error in morbidty (uncmomid coded as 12577 rather than 12290)
sum(duplicated(morbidty$uncmomid))
match(TRUE, duplicated(morbidty$uncmomid))
morbidty[1637, 1:10]
hhold[hhold$uncmomid==12290, 1:10]
hhold[hhold$uncmomid==12577, 1:10]
morbidty[morbidty$uncmomid==12577, 1:10]
morbidty[805, "uncmomid"] <- 12290

# Merge 2002 Data
common_columns <- c("basebrgy", "basehhno", "basewman", "uncmomid", "BRGAY02","HHNUMB02","WOMAN02", "MOMCH02")
data_2002 <- merge(hhold, morbidty, by = common_columns)
data_2002 <- merge(data_2002, mother, by = common_columns)
data_2002 <- merge(data_2002, person, by = common_columns)
data_2002 <- merge(data_2002, secreen, by = common_columns)


# Retrieve women who died or moved since the last interview
## 228 moved (113 of which are not in data_2002), 48 died (all of which are not in data_2002)
moved_2002 <- subset(secreen, notinhh==2)
died_2002 <- subset(secreen, notinhh==1)
length(setdiff(unique(moved_2002$uncmomid), unique(data_2002$uncmomid)))
length(setdiff(unique(died_2002$uncmomid), unique(data_2002$uncmomid)))

# Change variable names to lowercase
names(data_2002) <- tolower(names(data_2002)) 
names(moved_2002) <- tolower(names(moved_2002)) 
names(died_2002) <- tolower(names(died_2002)) 

# Select columns of interest
var_2002 <- readLines("Data Scripts/variables_2002.txt")
names(data_2002)[names(data_2002) == 'maristat.x'] <- 'maristat'
data_2002 <- subset(data_2002, select=var_2002)

# Replace -9 values with "NA"
data_2002[data_2002==-9] <- NA

# Create new columns
## SRH index (0 for poor health, 1 for good or excellent)
data_2002$srh <- ifelse(data_2002$genhealt >= 2, 1, 0)
## education index (hs and college, 0 for none, 1 for at least one year)
data_2002$hs <- ifelse(data_2002$gradecom >= 8, 1, 0)
data_2002$college <- ifelse(data_2002$gradecom >= 12, 1, 0)
## assets index
### scale from 0-4, 1 point each for ownership of vehicle (cars, trucks), aircon, fridge, TV
data_2002$vehicle <- data_2002$cars + data_2002$trucks
data_2002$vehicleI <- ifelse(data_2002$vehicle >= 1, 1, 0)
data_2002$tv <- data_2002$colortv + data_2002$tvcable
data_2002$tvI <- ifelse(data_2002$tv >= 1, 1, 0)
data_2002$refrigerI <- ifelse(data_2002$refriger >= 1, 1, 0)
data_2002$airconI <- ifelse(data_2002$aircon >= 1, 1, 0)
data_2002$assets <- data_2002$vehicleI + data_2002$tvI + data_2002$refrigerI + data_2002$airconI
## illness index
data_2002$illness <- data_2002$diabete + data_2002$heartdis + data_2002$cancer + data_2002$tubercu + data_2002$hblood + data_2002$goiter + data_2002$anemia + data_2002$hepatiti + data_2002$arthriti + data_2002$utracti + data_2002$std + data_2002$pregprob
## functional limitations index
data_2002$hhchoresI <- ifelse(data_2002$hhchores >= 2, 1, 0)
data_2002$standI <- ifelse(data_2002$stand >= 2, 1, 0)
data_2002$walk1kmI <- ifelse(data_2002$walk1km >= 2, 1, 0)
data_2002$climbI <- ifelse(data_2002$climb >= 2, 1, 0)
data_2002$carrywtI <- ifelse(data_2002$carrywt >= 2, 1, 0)
data_2002$funclim <- data_2002$hhchoresI + data_2002$standI + data_2002$walk1kmI + data_2002$climbI + data_2002$carrywtI
## recode smoking and alcohol
data_2002$smoking <- ifelse(data_2002$smoke <= 0, 0, 1)
data_2002$alcohol <- ifelse(data_2002$drink <= 1, 0, 1)
## mental / emotional health index
data_2002$headacheI <- ifelse(data_2002$headache >= 2, 1, 0)
data_2002$digestnI <- ifelse(data_2002$digestn >= 2, 1, 0)
data_2002$diffslepI <- ifelse(data_2002$diffslep >= 2, 1, 0)
data_2002$lonelyI <- ifelse(data_2002$lonely >= 2, 1, 0)
data_2002$unfrndlyI <- ifelse(data_2002$unfrndly >= 2, 1, 0)
data_2002$worriedI <- ifelse(data_2002$worried >= 2, 1, 0)
data_2002$overcomeI <- ifelse(data_2002$overcome >= 2, 1, 0)
data_2002$dislikedI <- ifelse(data_2002$disliked >= 2, 1, 0)
data_2002$worthlesI <- ifelse(data_2002$worthles >= 2, 1, 0)
data_2002$livingI <- ifelse(data_2002$living >= 2, 1, 0)
data_2002$wishdeadI <- ifelse(data_2002$wishdead >= 2, 1, 0)
data_2002$takelifeI <- ifelse(data_2002$takelife >= 2, 1, 0)
data_2002$depress <- data_2002$headacheI + data_2002$digestnI + data_2002$diffslepI + data_2002$lonelyI + data_2002$unfrndlyI + data_2002$worriedI + data_2002$overcomeI + data_2002$dislikedI + data_2002$worthlesI + data_2002$livingI + data_2002$wishdeadI + data_2002$takelifeI
## BMI (1 NA for weightma, 3 NA for heightma, 30 pregnant, 33 NA for bmi)
#### no BMI for pregnant women
data_2002[data_2002$weightma <= 0, "weightma"] <- NA
data_2002[data_2002$heightma <= 0, "heightma"] <- NA
data_2002$bmi <- data_2002$weightma / (data_2002$heightma/100)^2
data_2002[data_2002$pregnow == 1, "bmi"] <- NA
data_2002$bmicat <- ifelse(data_2002$bmi < 18.5, "underweight", ifelse(data_2002$bmi >= 18.5 & data_2002$bmi < 25, "normal", ifelse(data_2002$bmi >= 25 & data_2002$bmi < 30, "overweight", "obese")))

# Drop unwanted data and values from environment
rm(hhold, morbidty, mother, person, secreen, common_columns, var_2002)

# Sort based on uncmomid
data_2002 <- data_2002[order(data_2002$uncmomid), ] 

# Save data
save(data_2002, file="data_2002.rda")